In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
sciezka_pliku_bundesliga_goals = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Bundesliga_goals.csv'

In [4]:
bundesliga_goals = pd.read_csv(sciezka_pliku_bundesliga_goals)

In [5]:
print(bundesliga_goals)

      Rk            Player  Nation   Pos           Squad     Age  Born   90s  \
0      1   Paxten Aaronson  us USA  MFDF  Eint Frankfurt  19-266  2003   1.6
1      2    Sargis Adamyan  am ARM  FWMF            Köln  29-361  1993   7.2
2      3     Karim Adeyemi  de GER  FWMF        Dortmund  21-121  2002  14.2
3      4        Amine Adli  fr FRA  FWMF      Leverkusen  23-009  2000  15.1
4      5         Felix Agu  de GER  DFFW   Werder Bremen  23-234  1999   0.5
..   ...               ...     ...   ...             ...     ...   ...   ...
503  504   Rodrigo Zalazar  uy URU  MFFW      Schalke 04  23-280  1999  13.2
504  505     Aaron Zehnter  de GER    DF        Augsburg  18-200  2004   0.0
505  506     Robin Zentner  de GER    GK        Mainz 05  28-203  1994  26.0
506  507  Michael Zetterer  de GER    GK   Werder Bremen  27-311  1995   1.7
507  508      Simon Zoller  de GER  FWMF          Bochum  31-327  1991  16.0

     SCA  SCA90  ...  GCA  GCA90  PassLive.1  PassDead.1  TO.1  Sh.1  Fld.1  \
0      7   4.47  ...    1   0.64           0           0     0     1      0
1     22   3.07  ...    3   0.42           1           0     0     2      0
2     54   3.81  ...   12   0.85           9           0     2     1      0
3     52   3.43  ...   11   0.73           6           0     3     0      2
4      4   7.20  ...    0   0.00           0           0     0     0      0
..   ...    ...  ...  ...    ...         ...         ...   ...   ...    ...
503   57   4.32  ...    6   0.45           5           1     0     0      0
504    0   0.00  ...    0   0.00           0           0     0     0      0
505    9   0.35  ...    2   0.08           1           1     0     0      0
506    0   0.00  ...    0   0.00           0           0     0     0      0
507   18   1.13  ...    1   0.06           1           0     0     0      0

     Def.1  Matches     -9999
0        0  Matches  4cd41883
1        0  Matches  22919e97
2        0  Matches  501055d8
3        0  Matches  dcfb17f4
4        0  Matches  cb6d81b3
..     ...      ...       ...
503      0  Matches  fc3697dd
504      0  Matches  65bf7e2b
505      0  Matches  5c4bf6ba
506      0  Matches  9b688ae1
507      0  Matches  29f7cfd9

[508 rows x 26 columns]

In [6]:
bundesliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1,Matches,-9999
0,1,Paxten Aaronson,us USA,MFDF,Eint Frankfurt,19-266,2003,1.6,7,4.47,...,1,0.64,0,0,0,1,0,0,Matches,4cd41883
1,2,Sargis Adamyan,am ARM,FWMF,Köln,29-361,1993,7.2,22,3.07,...,3,0.42,1,0,0,2,0,0,Matches,22919e97
2,3,Karim Adeyemi,de GER,FWMF,Dortmund,21-121,2002,14.2,54,3.81,...,12,0.85,9,0,2,1,0,0,Matches,501055d8
3,4,Amine Adli,fr FRA,FWMF,Leverkusen,23-009,2000,15.1,52,3.43,...,11,0.73,6,0,3,0,2,0,Matches,dcfb17f4
4,5,Felix Agu,de GER,DFFW,Werder Bremen,23-234,1999,0.5,4,7.20,...,0,0.00,0,0,0,0,0,0,Matches,cb6d81b3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,504,Rodrigo Zalazar,uy URU,MFFW,Schalke 04,23-280,1999,13.2,57,4.32,...,6,0.45,5,1,0,0,0,0,Matches,fc3697dd
504,505,Aaron Zehnter,de GER,DF,Augsburg,18-200,2004,0.0,0,0.00,...,0,0.00,0,0,0,0,0,0,Matches,65bf7e2b
505,506,Robin Zentner,de GER,GK,Mainz 05,28-203,1994,26.0,9,0.35,...,2,0.08,1,1,0,0,0,0,Matches,5c4bf6ba
506,507,Michael Zetterer,de GER,GK,Werder Bremen,27-311,1995,1.7,0,0.00,...,0,0.00,0,0,0,0,0,0,Matches,9b688ae1
507,508,Simon Zoller,de GER,FWMF,Bochum,31-327,1991,16.0,18,1.13,...,1,0.06,1,0,0,0,0,0,Matches,29f7cfd9

In [7]:
del bundesliga_goals['Matches']
del bundesliga_goals['-9999']

In [8]:
bundesliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
0,1,Paxten Aaronson,us USA,MFDF,Eint Frankfurt,19-266,2003,1.6,7,4.47,...,1,0,1,0.64,0,0,0,1,0,0
1,2,Sargis Adamyan,am ARM,FWMF,Köln,29-361,1993,7.2,22,3.07,...,0,0,3,0.42,1,0,0,2,0,0
2,3,Karim Adeyemi,de GER,FWMF,Dortmund,21-121,2002,14.2,54,3.81,...,4,2,12,0.85,9,0,2,1,0,0
3,4,Amine Adli,fr FRA,FWMF,Leverkusen,23-009,2000,15.1,52,3.43,...,7,1,11,0.73,6,0,3,0,2,0
4,5,Felix Agu,de GER,DFFW,Werder Bremen,23-234,1999,0.5,4,7.20,...,0,0,0,0.00,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,504,Rodrigo Zalazar,uy URU,MFFW,Schalke 04,23-280,1999,13.2,57,4.32,...,7,0,6,0.45,5,1,0,0,0,0
504,505,Aaron Zehnter,de GER,DF,Augsburg,18-200,2004,0.0,0,0.00,...,0,0,0,0.00,0,0,0,0,0,0
505,506,Robin Zentner,de GER,GK,Mainz 05,28-203,1994,26.0,9,0.35,...,0,0,2,0.08,1,1,0,0,0,0
506,507,Michael Zetterer,de GER,GK,Werder Bremen,27-311,1995,1.7,0,0.00,...,0,0,0,0.00,0,0,0,0,0,0
507,508,Simon Zoller,de GER,FWMF,Bochum,31-327,1991,16.0,18,1.13,...,1,0,1,0.06,1,0,0,0,0,0

In [10]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'

In [13]:
bundesliga_goals = bundesliga_goals[(bundesliga_goals['Pos'] == pos_1) | (bundesliga_goals['Pos'] == pos_2) | (bundesliga_goals['Pos'] == pos_3) | (bundesliga_goals['Pos'] == pos_4)]

In [14]:
bundesliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
20,21,Fisnik Asllani,xk KVX,FW,Hoffenheim,20-284,2002,1.9,8,4.29,...,1,1,1,0.54,1,0,0,0,0,0
29,30,Gil Bastião Dias,pt POR,FW,Stuttgart,26-233,1996,4.4,12,2.72,...,1,1,1,0.23,1,0,0,0,0,0
37,38,Sheraldo Becker,sr SUR,FW,Union Berlin,28-099,1995,26.4,82,3.11,...,6,0,12,0.45,11,0,0,1,0,0
38,39,Kevin Behrens,de GER,FW,Union Berlin,32-105,1991,15.2,43,2.83,...,4,1,7,0.46,4,0,2,0,1,0
43,44,Mergim Berisha,de GER,FW,Augsburg,25-008,1998,18.3,34,1.85,...,1,1,7,0.38,2,3,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,461,Marcus Thuram,fr FRA,FW,M'Gladbach,25-286,1997,26.1,60,2.29,...,4,3,10,0.38,5,0,2,2,1,0
461,462,Steffen Tigges,de GER,FW,Köln,24-292,1998,17.1,34,1.99,...,2,0,3,0.18,2,0,0,1,0,0
480,481,Gabriel Vidovic,hr CRO,FW,Bayern Munich,19-169,2003,0.2,2,9.47,...,0,0,1,4.74,1,0,0,0,0,0
494,495,Jonas Wind,dk DEN,FW,Wolfsburg,24-101,1999,12.6,34,2.70,...,2,0,6,0.48,4,0,0,1,1,0
497,498,Hannes Wolf,at AUT,FW,M'Gladbach,24-033,1999,4.8,13,2.73,...,1,0,1,0.21,1,0,0,0,0,0

In [17]:
sciezka_pliku_bundesliga_goals_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/Players_Bundesliga_goals_final.xlsx'

In [18]:
bundesliga_goals.to_excel(sciezka_pliku_bundesliga_goals_final, index =False)

La Liga Goals

In [19]:
sciezka_pliku_laliga_goals = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_La Liga_goals.csv'

In [20]:
laliga_goals = pd.read_csv(sciezka_pliku_laliga_goals)

In [21]:
laliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1,Matches,-9999
0,1,Abner,br BRA,DF,Betis,22-357,2000,4.9,7.0,1.44,...,1.0,0.21,1.0,0.0,0.0,0.0,0.0,0.0,Matches,7f9c5d2d
1,2,Álvaro Aceves,es ESP,GK,Valladolid,19-297,2003,0.1,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,be6faae0
2,3,Marcos Acuña,ar ARG,DF,Sevilla,31-203,1991,19.4,59.0,3.03,...,4.0,0.21,4.0,0.0,0.0,0.0,0.0,0.0,Matches,81442ecb
3,4,Julen Agirrezabala,es ESP,GK,Athletic Club,22-144,2000,6.5,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,a2c1a8d3
4,5,Álvaro Aguado,es ESP,MF,Valladolid,27-018,1996,17.8,65.0,3.65,...,4.0,0.22,2.0,2.0,0.0,0.0,0.0,0.0,Matches,014aa7bd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Jawad El Yamiq,ma MAR,DF,Valladolid,31-079,1992,16.0,9.0,0.54,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,f6f6b6e8
581,582,Joseba Zaldúa,es ESP,DF,Cádiz,30-329,1992,7.1,7.0,0.99,...,1.0,0.14,1.0,0.0,0.0,0.0,0.0,0.0,Matches,5ca20b7a
582,583,Oier Zarraga,es ESP,MF,Athletic Club,24-135,1999,8.1,22.0,2.72,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,968a1c2f
583,584,Igor Zubeldia,es ESP,DF,Real Sociedad,26-050,1997,25.4,10.0,0.39,...,2.0,0.08,2.0,0.0,0.0,0.0,0.0,0.0,Matches,5c7845f6
584,585,Martín Zubimendi,es ESP,MF,Real Sociedad,24-106,1999,30.8,43.0,1.40,...,4.0,0.13,4.0,0.0,0.0,0.0,0.0,0.0,Matches,3ee0dd59

In [22]:
del laliga_goals['Matches']
del laliga_goals['-9999']

In [23]:
laliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
0,1,Abner,br BRA,DF,Betis,22-357,2000,4.9,7.0,1.44,...,0.0,0.0,1.0,0.21,1.0,0.0,0.0,0.0,0.0,0.0
1,2,Álvaro Aceves,es ESP,GK,Valladolid,19-297,2003,0.1,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Marcos Acuña,ar ARG,DF,Sevilla,31-203,1991,19.4,59.0,3.03,...,0.0,0.0,4.0,0.21,4.0,0.0,0.0,0.0,0.0,0.0
3,4,Julen Agirrezabala,es ESP,GK,Athletic Club,22-144,2000,6.5,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Álvaro Aguado,es ESP,MF,Valladolid,27-018,1996,17.8,65.0,3.65,...,3.0,0.0,4.0,0.22,2.0,2.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Jawad El Yamiq,ma MAR,DF,Valladolid,31-079,1992,16.0,9.0,0.54,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
581,582,Joseba Zaldúa,es ESP,DF,Cádiz,30-329,1992,7.1,7.0,0.99,...,1.0,1.0,1.0,0.14,1.0,0.0,0.0,0.0,0.0,0.0
582,583,Oier Zarraga,es ESP,MF,Athletic Club,24-135,1999,8.1,22.0,2.72,...,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
583,584,Igor Zubeldia,es ESP,DF,Real Sociedad,26-050,1997,25.4,10.0,0.39,...,0.0,1.0,2.0,0.08,2.0,0.0,0.0,0.0,0.0,0.0
584,585,Martín Zubimendi,es ESP,MF,Real Sociedad,24-106,1999,30.8,43.0,1.40,...,3.0,1.0,4.0,0.13,4.0,0.0,0.0,0.0,0.0,0.0

In [24]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'

In [25]:
laliga_goals = laliga_goals[(laliga_goals['Pos'] == pos_1) | (laliga_goals['Pos'] == pos_2) | (laliga_goals['Pos'] == pos_3) | (laliga_goals['Pos'] == pos_4)]

In [26]:
laliga_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
7,8,Babatunde Akinsola,ng NGA,FW,Valladolid,20-070,2003,0.1,1.0,8.18,...,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
20,21,Mohamed Ali Cho,fr FRA,FW,Real Sociedad,19-120,2004,5.5,17.0,3.10,...,1.0,1.0,2.0,0.37,2.0,0.0,0.0,0.0,0.0,0.0
23,24,Carlos Álvarez,es ESP,FW,Sevilla,19-286,2003,0.1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,Iago Aspas,es ESP,FW,Celta Vigo,35-291,1987,31.3,137.0,4.38,...,9.0,1.0,8.0,0.26,8.0,0.0,0.0,0.0,0.0,0.0
41,42,Pierre-Emerick Aubameyang,ga GAB,FW,Barcelona,33-335,1989,0.1,1.0,10.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,571,Asier Villalibre,es ESP,FW,Athletic Club,25-231,1997,1.1,3.0,2.73,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
574,575,Shon Weissman,il ISR,FW,Valladolid,27-094,1996,8.3,4.0,0.48,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
576,577,Iñaki Williams,gh GHA,FW,Athletic Club,28-338,1994,27.7,74.0,2.67,...,3.0,0.0,8.0,0.29,6.0,0.0,1.0,0.0,1.0,0.0
577,578,Nico Williams,es ESP,FW,Athletic Club,20-311,2002,27.5,97.0,3.52,...,4.0,1.0,9.0,0.33,5.0,0.0,2.0,1.0,1.0,0.0
579,580,Lamine Yamal,es ESP,FW,Barcelona,15-310,2007,0.1,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
sciezka_pliku_laliga_goals_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/Players_laliga_goals_final.xlsx'

In [28]:
laliga_goals.to_excel(sciezka_pliku_laliga_goals_final, index =False)

Ligue 1 goals

In [45]:
sciezka_pliku_Ligue1_goals = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Ligue 1_goals.csv'

In [46]:
Ligue1_goals = pd.read_csv(sciezka_pliku_Ligue1_goals)

In [47]:
Ligue1_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1,Matches,-9999
0,1,Yunis Abdelhamid,ma MAR,DF,Reims,35-233,1987,35.0,40.0,1.14,...,6.0,0.17,3.0,0.0,2.0,1.0,0.0,0.0,Matches,32c2d95f
1,2,Himad Abdelli,fr FRA,MFFW,Angers,23-183,1999,20.8,62.0,2.98,...,3.0,0.14,3.0,0.0,0.0,0.0,0.0,0.0,Matches,7978cbf0
2,3,Salis Abdul Samed,gh GHA,MF,Lens,23-054,2000,29.2,47.0,1.61,...,1.0,0.03,1.0,0.0,0.0,0.0,0.0,0.0,Matches,82464ce3
3,4,Laurent Abergel,fr FRA,MF,Lorient,30-107,1993,23.1,31.0,1.34,...,1.0,0.04,1.0,0.0,0.0,0.0,0.0,0.0,Matches,31626657
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,13.0,1.51,...,3.0,0.35,1.0,0.0,1.0,0.0,1.0,0.0,Matches,0e46fa2f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,586,Mehdi Zeffane,dz ALG,DFMF,Clermont Foot,31-000,1992,5.7,11.0,1.92,...,1.0,0.17,1.0,0.0,0.0,0.0,0.0,0.0,Matches,c8c02ac7
586,587,Arber Zeneli,xk KVX,FWMF,Reims,28-083,1995,11.1,47.0,4.23,...,7.0,0.63,5.0,0.0,0.0,1.0,1.0,0.0,Matches,095e4199
587,588,Nathan Zeze,fr FRA,DF,Nantes,17-335,2005,0.7,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,fb4c5b6e
588,589,Edon Zhegrova,xk KVX,FWDF,Lille,24-049,1999,11.5,72.0,6.23,...,11.0,0.95,6.0,2.0,0.0,2.0,1.0,0.0,Matches,34a88e3e
589,590,Banhie Zoukrou,fr FRA,DF,Troyes,20-012,2003,4.7,3.0,0.64,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,aefa3050

In [48]:
del Ligue1_goals['Matches']
del Ligue1_goals['-9999']

In [49]:
Ligue1_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
0,1,Yunis Abdelhamid,ma MAR,DF,Reims,35-233,1987,35.0,40.0,1.14,...,0.0,2.0,6.0,0.17,3.0,0.0,2.0,1.0,0.0,0.0
1,2,Himad Abdelli,fr FRA,MFFW,Angers,23-183,1999,20.8,62.0,2.98,...,0.0,2.0,3.0,0.14,3.0,0.0,0.0,0.0,0.0,0.0
2,3,Salis Abdul Samed,gh GHA,MF,Lens,23-054,2000,29.2,47.0,1.61,...,2.0,1.0,1.0,0.03,1.0,0.0,0.0,0.0,0.0,0.0
3,4,Laurent Abergel,fr FRA,MF,Lorient,30-107,1993,23.1,31.0,1.34,...,0.0,1.0,1.0,0.04,1.0,0.0,0.0,0.0,0.0,0.0
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,13.0,1.51,...,1.0,0.0,3.0,0.35,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,586,Mehdi Zeffane,dz ALG,DFMF,Clermont Foot,31-000,1992,5.7,11.0,1.92,...,1.0,0.0,1.0,0.17,1.0,0.0,0.0,0.0,0.0,0.0
586,587,Arber Zeneli,xk KVX,FWMF,Reims,28-083,1995,11.1,47.0,4.23,...,2.0,0.0,7.0,0.63,5.0,0.0,0.0,1.0,1.0,0.0
587,588,Nathan Zeze,fr FRA,DF,Nantes,17-335,2005,0.7,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
588,589,Edon Zhegrova,xk KVX,FWDF,Lille,24-049,1999,11.5,72.0,6.23,...,4.0,2.0,11.0,0.95,6.0,2.0,0.0,2.0,1.0,0.0
589,590,Banhie Zoukrou,fr FRA,DF,Troyes,20-012,2003,4.7,3.0,0.64,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'

In [54]:
Ligue1_goals = Ligue1_goals[(Ligue1_goals['Pos'] == pos_1) | (Ligue1_goals['Pos'] == pos_2) | (Ligue1_goals['Pos'] == pos_3) | (Ligue1_goals['Pos'] == pos_4)]

In [55]:
Ligue1_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,13.0,1.51,...,1.0,0.0,3.0,0.35,1.0,0.0,1.0,0.0,1.0,0.0
7,8,Mohamed Achi,fr FRA,FW,Nantes,21-123,2002,0.4,1.0,2.50,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
12,13,Amar Ahmed,se SWE,FW,Troyes,19-089,2004,0.2,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
14,15,Ludovic Ajorque,fr FRA,FW,Strasbourg,29-083,1994,8.6,22.0,2.57,...,0.0,0.0,2.0,0.23,1.0,0.0,0.0,1.0,0.0,0.0
22,23,Komnen Andrić,rs SRB,FW,Clermont Foot,27-322,1995,15.7,31.0,1.97,...,2.0,0.0,4.0,0.25,2.0,0.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,519,Moussa Soumano,fr FRA,FW,Ajaccio,17-314,2005,4.6,10.0,2.15,...,1.0,0.0,1.0,0.22,0.0,0.0,1.0,0.0,0.0,0.0
523,524,Calvin Stengs,nl NED,FW,Nice,24-152,1998,2.4,9.0,3.82,...,0.0,0.0,1.0,0.42,1.0,0.0,0.0,0.0,0.0,0.0
552,553,Yoann Touzghar,tn TUN,FW,Ajaccio,36-172,1986,5.0,2.0,0.40,...,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
567,568,Alan Virginius,fr FRA,FW,Lille,20-136,2003,2.9,8.0,2.78,...,1.0,0.0,1.0,0.35,0.0,0.0,0.0,1.0,0.0,0.0
569,570,Vitinha,pt POR,FW,Marseille,23-065,2000,4.1,11.0,2.65,...,1.0,0.0,1.0,0.24,0.0,0.0,1.0,0.0,0.0,0.0

In [57]:
sciezka_pliku_Ligue1_goals_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/Players_Ligue1_goals_final.xlsx'

In [58]:
Ligue1_goals.to_excel(sciezka_pliku_Ligue1_goals_final, index =False)

Premier League (PL)

In [59]:
sciezka_pliku_PL_goals = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_PL_goals.csv'

In [60]:
PL_goals = pd.read_csv(sciezka_pliku_PL_goals)

In [61]:
PL_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1,Matches,-9999
0,1,Brenden Aaronson,us USA,MFFW,Leeds United,22-208,2000,25.7,94,3.66,...,7,0.27,3,1,0,1,1,1,Matches,5bc43860
1,2,Che Adams,sct SCO,FW,Southampton,26-309,1996,22.1,57,2.57,...,7,0.32,5,0,0,0,2,0,Matches,f2bf1b0f
2,3,Tyler Adams,us USA,MF,Leeds United,24-093,1999,24.0,43,1.79,...,1,0.04,1,0,0,0,0,0,Matches,2b09d998
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25-236,1997,21.2,17,0.80,...,0,0.00,0,0,0,0,0,0,Matches,c81d773d
4,5,Nayef Aguerd,ma MAR,DF,West Ham,27-049,1996,16.7,13,0.78,...,0,0.00,0,0,0,0,0,0,Matches,288e1e13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,554,Jordan Zemura,zw ZIM,DF,Bournemouth,23-185,1999,16.2,35,2.17,...,2,0.12,2,0,0,0,0,0,Matches,e8271ad9
554,555,Oleksandr Zinchenko,ua UKR,DF,Arsenal,26-154,1996,23.5,56,2.38,...,4,0.17,3,0,0,1,0,0,Matches,51cf8561
555,556,Hakim Ziyech,ma MAR,FWMF,Chelsea,30-060,1993,7.2,30,4.14,...,2,0.28,1,1,0,0,0,0,Matches,6622454d
556,557,Kurt Zouma,fr FRA,DF,West Ham,28-203,1994,21.6,9,0.42,...,2,0.09,1,0,0,1,0,0,Matches,ce4246f5
557,558,Martin Ødegaard,no NOR,MF,Arsenal,24-152,1998,32.9,155,4.71,...,16,0.49,14,0,0,2,0,0,Matches,79300479

In [63]:
del PL_goals['Matches']
del PL_goals['-9999']

In [64]:
PL_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
0,1,Brenden Aaronson,us USA,MFFW,Leeds United,22-208,2000,25.7,94,3.66,...,8,1,7,0.27,3,1,0,1,1,1
1,2,Che Adams,sct SCO,FW,Southampton,26-309,1996,22.1,57,2.57,...,5,0,7,0.32,5,0,0,0,2,0
2,3,Tyler Adams,us USA,MF,Leeds United,24-093,1999,24.0,43,1.79,...,1,0,1,0.04,1,0,0,0,0,0
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25-236,1997,21.2,17,0.80,...,0,0,0,0.00,0,0,0,0,0,0
4,5,Nayef Aguerd,ma MAR,DF,West Ham,27-049,1996,16.7,13,0.78,...,0,0,0,0.00,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,554,Jordan Zemura,zw ZIM,DF,Bournemouth,23-185,1999,16.2,35,2.17,...,2,0,2,0.12,2,0,0,0,0,0
554,555,Oleksandr Zinchenko,ua UKR,DF,Arsenal,26-154,1996,23.5,56,2.38,...,1,1,4,0.17,3,0,0,1,0,0
555,556,Hakim Ziyech,ma MAR,FWMF,Chelsea,30-060,1993,7.2,30,4.14,...,1,1,2,0.28,1,1,0,0,0,0
556,557,Kurt Zouma,fr FRA,DF,West Ham,28-203,1994,21.6,9,0.42,...,0,0,2,0.09,1,0,0,1,0,0
557,558,Martin Ødegaard,no NOR,MF,Arsenal,24-152,1998,32.9,155,4.71,...,6,3,16,0.49,14,0,0,2,0,0

In [65]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AM,FW'
pos_4 = 'FW,AM'

In [66]:
PL_goals = PL_goals[(PL_goals['Pos'] == pos_1) | (PL_goals['Pos'] == pos_2) | (PL_goals['Pos'] == pos_3) | (PL_goals['Pos'] == pos_4)]

In [67]:
PL_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
1,2,Che Adams,sct SCO,FW,Southampton,26-309,1996,22.1,57,2.57,...,5,0,7,0.32,5,0,0,0,2,0
16,17,Miguel Almirón,py PAR,FW,Newcastle Utd,29-097,1994,24.7,74,2.99,...,3,0,11,0.45,4,1,4,2,0,0
22,23,Michail Antonio,jm JAM,FW,West Ham,33-051,1990,19.6,38,1.93,...,5,0,9,0.46,6,0,2,1,0,0
23,24,Antony,br BRA,FW,Manchester Utd,23-083,2000,18.8,71,3.78,...,3,1,7,0.37,6,0,1,0,0,0
30,31,Pierre-Emerick Aubameyang,ga GAB,FW,Chelsea,33-334,1989,6.2,8,1.30,...,0,0,0,0.00,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,541,Callum Wilson,eng ENG,FW,Newcastle Utd,31-080,1992,18.9,35,1.86,...,5,0,8,0.42,4,0,2,2,0,0
541,542,Harry Wilson,wls WAL,FW,Fulham,26-057,1997,10.6,28,2.64,...,6,0,7,0.66,4,0,0,1,2,0
542,543,Yoane Wissa,cd COD,FW,Brentford,26-257,1996,15.9,32,2.02,...,3,1,5,0.31,3,0,0,0,1,1
544,545,Chris Wood,nz NZL,FW,Newcastle Utd,31-162,1991,5.0,5,1.01,...,0,0,0,0.00,0,0,0,0,0,0
545,546,Chris Wood,nz NZL,FW,Nott'ham Forest,31-162,1991,4.1,6,1.45,...,1,0,0,0.00,0,0,0,0,0,0

In [69]:
sciezka_pliku_PL_goals_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/Players_PL_goals_final.xlsx'

In [70]:
PL_goals.to_excel(sciezka_pliku_PL_goals_final, index =False)

Serie A

In [71]:
sciezka_pliku_SerieA_goals = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Serie A_goals.csv'

In [72]:
SerieA_goals = pd.read_csv(sciezka_pliku_SerieA_goals)

In [73]:
SerieA_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1,Matches,-9999
0,1,James Abankwah,ie IRL,DF,Udinese,19-123,2004,0.1,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,4b7a9fcc
1,2,Oliver Abildgaard,dk DEN,MF,Hellas Verona,26-343,1996,6.2,8.0,1.29,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,8f5cdf66
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,68.0,2.86,...,9.0,0.38,4.0,0.0,1.0,3.0,1.0,0.0,Matches,f586779e
3,4,Christian Acella,it ITA,MF,Cremonese,20-316,2002,0.2,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,771a2cfe
4,5,Francesco Acerbi,it ITA,DF,Inter,35-098,1988,25.3,37.0,1.46,...,1.0,0.04,1.0,0.0,0.0,0.0,0.0,0.0,Matches,b96b595c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Petar Zovko,ba BIH,GK,Spezia,21-055,2002,0.8,0.0,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,54f6afe3
581,582,Szymon Żurkowski,pl POL,MF,Fiorentina,25-236,1997,0.4,2.0,5.63,...,1.0,2.81,1.0,0.0,0.0,0.0,0.0,0.0,Matches,4e1d5e59
582,583,Szymon Żurkowski,pl POL,MF,Spezia,25-236,1997,3.0,2.0,0.67,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches,4e1d5e59
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,28.0,2.18,...,2.0,0.16,2.0,0.0,0.0,0.0,0.0,0.0,Matches,405f6586
584,585,Filip Đuričić,rs SRB,MFFW,Sampdoria,31-109,1992,23.2,69.0,2.98,...,3.0,0.13,3.0,0.0,0.0,0.0,0.0,0.0,Matches,eccbe56a

In [74]:
del SerieA_goals['Matches']
del SerieA_goals['-9999']

In [75]:
SerieA_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
0,1,James Abankwah,ie IRL,DF,Udinese,19-123,2004,0.1,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Oliver Abildgaard,dk DEN,MF,Hellas Verona,26-343,1996,6.2,8.0,1.29,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,68.0,2.86,...,7.0,0.0,9.0,0.38,4.0,0.0,1.0,3.0,1.0,0.0
3,4,Christian Acella,it ITA,MF,Cremonese,20-316,2002,0.2,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Francesco Acerbi,it ITA,DF,Inter,35-098,1988,25.3,37.0,1.46,...,0.0,0.0,1.0,0.04,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Petar Zovko,ba BIH,GK,Spezia,21-055,2002,0.8,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
581,582,Szymon Żurkowski,pl POL,MF,Fiorentina,25-236,1997,0.4,2.0,5.63,...,0.0,0.0,1.0,2.81,1.0,0.0,0.0,0.0,0.0,0.0
582,583,Szymon Żurkowski,pl POL,MF,Spezia,25-236,1997,3.0,2.0,0.67,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,28.0,2.18,...,2.0,0.0,2.0,0.16,2.0,0.0,0.0,0.0,0.0,0.0
584,585,Filip Đuričić,rs SRB,MFFW,Sampdoria,31-109,1992,23.2,69.0,2.98,...,6.0,2.0,3.0,0.13,3.0,0.0,0.0,0.0,0.0,0.0

In [76]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'

In [77]:
SerieA_goals = SerieA_goals[(SerieA_goals['Pos'] == pos_1) | (SerieA_goals['Pos'] == pos_2) | (SerieA_goals['Pos'] == pos_3) | (SerieA_goals['Pos'] == pos_4)]

In [78]:
SerieA_goals

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive.1,PassDead.1,TO.1,Sh.1,Fld.1,Def.1
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,68.0,2.86,...,7.0,0.0,9.0,0.38,4.0,0.0,1.0,3.0,1.0,0.0
19,20,Felipe Anderson,br BRA,FW,Lazio,30-034,1993,31.0,94.0,3.03,...,3.0,0.0,15.0,0.48,8.0,0.0,4.0,2.0,1.0,0.0
20,21,Janis Antiste,fr FRA,FW,Sassuolo,20-274,2002,0.6,0.0,0.00,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
23,24,Marko Arnautović,at AUT,FW,Bologna,34-030,1989,14.7,40.0,2.71,...,3.0,0.0,4.0,0.27,2.0,0.0,1.0,0.0,1.0,0.0
25,26,Arthur,br BRA,FW,Fiorentina,25-024,1998,14.9,34.0,2.28,...,3.0,0.0,2.0,0.13,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,560,Mattia Zaccagni,it ITA,FW,Lazio,27-337,1995,28.5,80.0,2.81,...,8.0,1.0,10.0,0.35,7.0,1.0,0.0,1.0,1.0,0.0
568,569,Duván Zapata,co COL,FW,Atalanta,32-048,1991,15.5,46.0,2.98,...,4.0,1.0,7.0,0.45,4.0,0.0,1.0,1.0,1.0,0.0
573,574,Alessio Zerbin,it ITA,FW,Napoli,24-077,1999,1.3,2.0,1.51,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
576,577,Joshua Zirkzee,nl NED,FW,Bologna,21-362,2001,8.6,34.0,3.96,...,1.0,1.0,4.0,0.47,4.0,0.0,0.0,0.0,0.0,0.0
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,28.0,2.18,...,2.0,0.0,2.0,0.16,2.0,0.0,0.0,0.0,0.0,0.0

In [81]:
sciezka_pliku_SerieA_goals_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/Players_SerieA_goals_final.xlsx'

In [83]:
SerieA_goals.to_excel(sciezka_pliku_SerieA_goals_final, index =False)

stworzenie jednego pliku

In [84]:
import glob

In [85]:
folder_path = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/'

In [86]:
files_xlsx = glob.glob(folder_path + '*.xlsx')

In [87]:
df_list =[]

In [90]:
for file in files_xlsx:
    df = pd.read_excel(file)
    df_list.append(df)

In [91]:
df_combined = pd.concat(df_list)

In [92]:
path_output_file = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po filtrowaniu/All_players_goals.xlsx'

In [93]:
df_combined.to_excel(path_output_file, index=False)

## SHOTS

Bundesliga

In [95]:
sciezka_pliku_bundesliga_shoots = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Bundesliga_shoots.csv'
bundesliga_shoots = pd.read_csv(sciezka_pliku_bundesliga_shoots)

In [96]:
bundesliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,-9999
0,1,Paxten Aaronson,us USA,MFDF,Eint Frankfurt,19-266,2003,1.6,0,4,...,0,0,0,0.2,0.2,0.04,-0.2,-0.2,Matches,4cd41883
1,2,Sargis Adamyan,am ARM,FWMF,Köln,29-361,1993,7.2,1,21,...,0,0,0,3.4,3.4,0.16,-2.4,-2.4,Matches,22919e97
2,3,Karim Adeyemi,de GER,FWMF,Dortmund,21-121,2002,14.2,6,34,...,0,0,1,4.9,4.1,0.12,1.1,1.9,Matches,501055d8
3,4,Amine Adli,fr FRA,FWMF,Leverkusen,23-009,2000,15.1,4,34,...,1,0,0,4.5,4.5,0.13,-0.5,-0.5,Matches,dcfb17f4
4,5,Felix Agu,de GER,DFFW,Werder Bremen,23-234,1999,0.5,0,1,...,0,0,0,0.0,0.0,0.04,0.0,0.0,Matches,cb6d81b3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,504,Rodrigo Zalazar,uy URU,MFFW,Schalke 04,23-280,1999,13.2,1,34,...,9,0,0,2.8,2.8,0.08,-1.8,-1.8,Matches,fc3697dd
504,505,Aaron Zehnter,de GER,DF,Augsburg,18-200,2004,0.0,0,0,...,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,65bf7e2b
505,506,Robin Zentner,de GER,GK,Mainz 05,28-203,1994,26.0,0,0,...,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,5c4bf6ba
506,507,Michael Zetterer,de GER,GK,Werder Bremen,27-311,1995,1.7,0,0,...,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,9b688ae1
507,508,Simon Zoller,de GER,FWMF,Bochum,31-327,1991,16.0,3,30,...,0,0,0,4.1,4.1,0.14,-1.1,-1.1,Matches,29f7cfd9

In [97]:
del bundesliga_shoots['Matches']
del bundesliga_shoots['-9999']

In [98]:
bundesliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,1,Paxten Aaronson,us USA,MFDF,Eint Frankfurt,19-266,2003,1.6,0,4,...,0.00,18.7,0,0,0,0.2,0.2,0.04,-0.2,-0.2
1,2,Sargis Adamyan,am ARM,FWMF,Köln,29-361,1993,7.2,1,21,...,0.09,14.0,0,0,0,3.4,3.4,0.16,-2.4,-2.4
2,3,Karim Adeyemi,de GER,FWMF,Dortmund,21-121,2002,14.2,6,34,...,0.43,17.2,0,0,1,4.9,4.1,0.12,1.1,1.9
3,4,Amine Adli,fr FRA,FWMF,Leverkusen,23-009,2000,15.1,4,34,...,0.27,14.1,1,0,0,4.5,4.5,0.13,-0.5,-0.5
4,5,Felix Agu,de GER,DFFW,Werder Bremen,23-234,1999,0.5,0,1,...,NaN,15.9,0,0,0,0.0,0.0,0.04,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,504,Rodrigo Zalazar,uy URU,MFFW,Schalke 04,23-280,1999,13.2,1,34,...,0.08,22.5,9,0,0,2.8,2.8,0.08,-1.8,-1.8
504,505,Aaron Zehnter,de GER,DF,Augsburg,18-200,2004,0.0,0,0,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
505,506,Robin Zentner,de GER,GK,Mainz 05,28-203,1994,26.0,0,0,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
506,507,Michael Zetterer,de GER,GK,Werder Bremen,27-311,1995,1.7,0,0,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
507,508,Simon Zoller,de GER,FWMF,Bochum,31-327,1991,16.0,3,30,...,0.33,12.6,0,0,0,4.1,4.1,0.14,-1.1,-1.1

In [99]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'
bundesliga_shoots = bundesliga_shoots[(bundesliga_shoots['Pos'] == pos_1) | (bundesliga_shoots['Pos'] == pos_2) | (bundesliga_shoots['Pos'] == pos_3) | (bundesliga_shoots['Pos'] == pos_4)]

In [100]:
bundesliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
20,21,Fisnik Asllani,xk KVX,FW,Hoffenheim,20-284,2002,1.9,0,9,...,NaN,11.1,0,0,0,1.7,1.7,0.19,-1.7,-1.7
29,30,Gil Bastião Dias,pt POR,FW,Stuttgart,26-233,1996,4.4,1,10,...,0.25,20.2,0,0,0,0.5,0.5,0.05,0.5,0.5
37,38,Sheraldo Becker,sr SUR,FW,Union Berlin,28-099,1995,26.4,11,59,...,0.44,18.3,0,0,0,5.3,5.3,0.09,5.7,5.7
38,39,Kevin Behrens,de GER,FW,Union Berlin,32-105,1991,15.2,8,31,...,0.57,12.1,0,0,0,4.4,4.4,0.14,3.6,3.6
43,44,Mergim Berisha,de GER,FW,Augsburg,25-008,1998,18.3,9,51,...,0.46,18.7,6,3,4,8.1,5.0,0.10,0.9,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,461,Marcus Thuram,fr FRA,FW,M'Gladbach,25-286,1997,26.1,13,85,...,0.30,12.7,0,0,0,15.1,15.1,0.18,-2.1,-2.1
461,462,Steffen Tigges,de GER,FW,Köln,24-292,1998,17.1,5,34,...,0.50,12.5,0,0,0,4.8,4.8,0.14,0.2,0.2
480,481,Gabriel Vidovic,hr CRO,FW,Bayern Munich,19-169,2003,0.2,0,0,...,NaN,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0
494,495,Jonas Wind,dk DEN,FW,Wolfsburg,24-101,1999,12.6,6,24,...,0.75,13.5,0,0,1,4.0,3.2,0.13,2.0,2.8
497,498,Hannes Wolf,at AUT,FW,M'Gladbach,24-033,1999,4.8,1,7,...,0.33,12.5,0,0,0,1.4,1.4,0.20,-0.4,-0.4

In [101]:
sciezka_pliku_bundesliga_shoots_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/Players_Bundesliga_shoots_final.xlsx'
bundesliga_shoots.to_excel(sciezka_pliku_bundesliga_shoots_final, index =False)

La Liga

In [102]:
sciezka_pliku_laliga_shoots = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_La Liga_shoots.csv'
laliga_shoots = pd.read_csv(sciezka_pliku_laliga_shoots)

In [103]:
laliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,-9999
0,1,Abner,br BRA,DF,Betis,22-357,2000,4.9,0,4,...,0.0,0,0,1.7,1.7,0.42,-1.7,-1.7,Matches,7f9c5d2d
1,2,Álvaro Aceves,es ESP,GK,Valladolid,19-297,2003,0.1,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,be6faae0
2,3,Marcos Acuña,ar ARG,DF,Sevilla,31-203,1991,19.4,3,20,...,1.0,0,0,1.1,1.1,0.06,1.9,1.9,Matches,81442ecb
3,4,Julen Agirrezabala,es ESP,GK,Athletic Club,22-144,2000,6.5,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,a2c1a8d3
4,5,Álvaro Aguado,es ESP,MF,Valladolid,27-018,1996,17.8,1,16,...,0.0,0,0,0.8,0.8,0.05,0.2,0.2,Matches,014aa7bd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Jawad El Yamiq,ma MAR,DF,Valladolid,31-079,1992,16.0,1,15,...,0.0,0,0,1.0,1.0,0.07,0.0,0.0,Matches,f6f6b6e8
581,582,Joseba Zaldúa,es ESP,DF,Cádiz,30-329,1992,7.1,0,1,...,0.0,0,0,0.0,0.0,0.01,0.0,0.0,Matches,5ca20b7a
582,583,Oier Zarraga,es ESP,MF,Athletic Club,24-135,1999,8.1,0,16,...,0.0,0,0,1.0,1.0,0.07,-1.0,-1.0,Matches,968a1c2f
583,584,Igor Zubeldia,es ESP,DF,Real Sociedad,26-050,1997,25.4,1,6,...,0.0,0,0,0.9,0.9,0.14,0.1,0.1,Matches,5c7845f6
584,585,Martín Zubimendi,es ESP,MF,Real Sociedad,24-106,1999,30.8,1,12,...,0.0,0,0,1.8,1.8,0.15,-0.8,-0.8,Matches,3ee0dd59

In [104]:
del laliga_shoots['Matches']
del laliga_shoots['-9999']
laliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,1,Abner,br BRA,DF,Betis,22-357,2000,4.9,0,4,...,0.00,8.2,0.0,0,0,1.7,1.7,0.42,-1.7,-1.7
1,2,Álvaro Aceves,es ESP,GK,Valladolid,19-297,2003,0.1,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
2,3,Marcos Acuña,ar ARG,DF,Sevilla,31-203,1991,19.4,3,20,...,0.60,25.4,1.0,0,0,1.1,1.1,0.06,1.9,1.9
3,4,Julen Agirrezabala,es ESP,GK,Athletic Club,22-144,2000,6.5,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
4,5,Álvaro Aguado,es ESP,MF,Valladolid,27-018,1996,17.8,1,16,...,0.20,24.1,0.0,0,0,0.8,0.8,0.05,0.2,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Jawad El Yamiq,ma MAR,DF,Valladolid,31-079,1992,16.0,1,15,...,0.25,20.8,0.0,0,0,1.0,1.0,0.07,0.0,0.0
581,582,Joseba Zaldúa,es ESP,DF,Cádiz,30-329,1992,7.1,0,1,...,NaN,32.7,0.0,0,0,0.0,0.0,0.01,0.0,0.0
582,583,Oier Zarraga,es ESP,MF,Athletic Club,24-135,1999,8.1,0,16,...,0.00,25.1,0.0,0,0,1.0,1.0,0.07,-1.0,-1.0
583,584,Igor Zubeldia,es ESP,DF,Real Sociedad,26-050,1997,25.4,1,6,...,1.00,14.5,0.0,0,0,0.9,0.9,0.14,0.1,0.1
584,585,Martín Zubimendi,es ESP,MF,Real Sociedad,24-106,1999,30.8,1,12,...,0.50,19.8,0.0,0,0,1.8,1.8,0.15,-0.8,-0.8

In [105]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'
laliga_shoots = laliga_shoots[(laliga_shoots['Pos'] == pos_1) | (laliga_shoots['Pos'] == pos_2) | (laliga_shoots['Pos'] == pos_3) | (laliga_shoots['Pos'] == pos_4)]

In [106]:
laliga_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
7,8,Babatunde Akinsola,ng NGA,FW,Valladolid,20-070,2003,0.1,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
20,21,Mohamed Ali Cho,fr FRA,FW,Real Sociedad,19-120,2004,5.5,0,18,...,0.00,18.3,0.0,0,0,1.4,1.4,0.08,-1.4,-1.4
23,24,Carlos Álvarez,es ESP,FW,Sevilla,19-286,2003,0.1,0,0,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
40,41,Iago Aspas,es ESP,FW,Celta Vigo,35-291,1987,31.3,12,74,...,0.34,19.4,6.0,2,3,11.0,8.7,0.12,1.0,1.3
41,42,Pierre-Emerick Aubameyang,ga GAB,FW,Barcelona,33-335,1989,0.1,0,1,...,NaN,12.4,0.0,0,0,0.1,0.1,0.12,-0.1,-0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,571,Asier Villalibre,es ESP,FW,Athletic Club,25-231,1997,1.1,0,4,...,0.00,11.6,0.0,0,0,0.3,0.3,0.08,-0.3,-0.3
574,575,Shon Weissman,il ISR,FW,Valladolid,27-094,1996,8.3,1,18,...,0.14,12.8,0.0,0,0,2.3,2.3,0.13,-1.3,-1.3
576,577,Iñaki Williams,gh GHA,FW,Athletic Club,28-338,1994,27.7,9,67,...,0.32,14.9,0.0,1,2,8.8,7.2,0.11,0.2,0.8
577,578,Nico Williams,es ESP,FW,Athletic Club,20-311,2002,27.5,6,59,...,0.30,17.8,1.0,0,0,4.8,4.8,0.08,1.2,1.2
579,580,Lamine Yamal,es ESP,FW,Barcelona,15-310,2007,0.1,0,1,...,0.00,10.9,0.0,0,0,0.4,0.4,0.35,-0.4,-0.4

In [107]:
sciezka_pliku_laliga_shoots_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/Players_Laliga_shoots_final.xlsx'
laliga_shoots.to_excel(sciezka_pliku_laliga_shoots_final, index =False)

Ligue 1

In [108]:
sciezka_pliku_ligue1_shoots = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Ligue 1_shoots.csv'
ligue1_shoots = pd.read_csv(sciezka_pliku_ligue1_shoots)

In [109]:
ligue1_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,-9999
0,1,Yunis Abdelhamid,ma MAR,DF,Reims,35-233,1987,35.0,1,31,...,0.0,0,0,2.3,2.3,0.07,-1.3,-1.3,Matches,32c2d95f
1,2,Himad Abdelli,fr FRA,MFFW,Angers,23-183,1999,20.8,0,19,...,1.0,0,0,1.2,1.2,0.06,-1.2,-1.2,Matches,7978cbf0
2,3,Salis Abdul Samed,gh GHA,MF,Lens,23-054,2000,29.2,1,13,...,0.0,0,0,0.9,0.9,0.07,0.1,0.1,Matches,82464ce3
3,4,Laurent Abergel,fr FRA,MF,Lorient,30-107,1993,23.1,0,11,...,0.0,0,0,0.4,0.4,0.04,-0.4,-0.4,Matches,31626657
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,2,21,...,0.0,1,2,3.2,1.7,0.08,-1.2,-0.7,Matches,0e46fa2f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,586,Mehdi Zeffane,dz ALG,DFMF,Clermont Foot,31-000,1992,5.7,0,4,...,0.0,0,0,0.3,0.3,0.08,-0.3,-0.3,Matches,c8c02ac7
586,587,Arber Zeneli,xk KVX,FWMF,Reims,28-083,1995,11.1,0,31,...,5.0,0,0,2.1,2.1,0.07,-2.1,-2.1,Matches,095e4199
587,588,Nathan Zeze,fr FRA,DF,Nantes,17-335,2005,0.7,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,fb4c5b6e
588,589,Edon Zhegrova,xk KVX,FWDF,Lille,24-049,1999,11.5,3,39,...,1.0,0,0,3.5,3.5,0.10,-0.5,-0.5,Matches,34a88e3e
589,590,Banhie Zoukrou,fr FRA,DF,Troyes,20-012,2003,4.7,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,aefa3050

In [110]:
del ligue1_shoots['Matches']
del ligue1_shoots['-9999']
ligue1_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,1,Yunis Abdelhamid,ma MAR,DF,Reims,35-233,1987,35.0,1,31,...,0.50,15.2,0.0,0,0,2.3,2.3,0.07,-1.3,-1.3
1,2,Himad Abdelli,fr FRA,MFFW,Angers,23-183,1999,20.8,0,19,...,0.00,21.4,1.0,0,0,1.2,1.2,0.06,-1.2,-1.2
2,3,Salis Abdul Samed,gh GHA,MF,Lens,23-054,2000,29.2,1,13,...,0.25,19.1,0.0,0,0,0.9,0.9,0.07,0.1,0.1
3,4,Laurent Abergel,fr FRA,MF,Lorient,30-107,1993,23.1,0,11,...,0.00,24.4,0.0,0,0,0.4,0.4,0.04,-0.4,-0.4
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,2,21,...,0.14,20.8,0.0,1,2,3.2,1.7,0.08,-1.2,-0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,586,Mehdi Zeffane,dz ALG,DFMF,Clermont Foot,31-000,1992,5.7,0,4,...,0.00,26.0,0.0,0,0,0.3,0.3,0.08,-0.3,-0.3
586,587,Arber Zeneli,xk KVX,FWMF,Reims,28-083,1995,11.1,0,31,...,0.00,20.8,5.0,0,0,2.1,2.1,0.07,-2.1,-2.1
587,588,Nathan Zeze,fr FRA,DF,Nantes,17-335,2005,0.7,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
588,589,Edon Zhegrova,xk KVX,FWDF,Lille,24-049,1999,11.5,3,39,...,0.23,18.3,1.0,0,0,3.5,3.5,0.10,-0.5,-0.5
589,590,Banhie Zoukrou,fr FRA,DF,Troyes,20-012,2003,4.7,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0

In [111]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AMFW'
pos_4 = 'FWAM'
ligue1_shoots = ligue1_shoots[(ligue1_shoots['Pos'] == pos_1) | (ligue1_shoots['Pos'] == pos_2) | (ligue1_shoots['Pos'] == pos_3) | (ligue1_shoots['Pos'] == pos_4)]

In [112]:
ligue1_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
4,5,Matthis Abline,fr FRA,FW,Auxerre,20-052,2003,8.6,2,21,...,0.14,20.8,0.0,1,2,3.2,1.7,0.08,-1.2,-0.7
7,8,Mohamed Achi,fr FRA,FW,Nantes,21-123,2002,0.4,0,1,...,NaN,26.1,0.0,0,0,0.1,0.1,0.12,-0.1,-0.1
12,13,Amar Ahmed,se SWE,FW,Troyes,19-089,2004,0.2,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
14,15,Ludovic Ajorque,fr FRA,FW,Strasbourg,29-083,1994,8.6,1,22,...,0.00,15.1,1.0,1,1,3.4,2.6,0.12,-2.4,-2.6
22,23,Komnen Andrić,rs SRB,FW,Clermont Foot,27-322,1995,15.7,4,28,...,0.27,14.4,0.0,1,2,5.5,3.9,0.14,-1.5,-0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,519,Moussa Soumano,fr FRA,FW,Ajaccio,17-314,2005,4.6,1,6,...,0.50,17.5,0.0,0,0,0.5,0.5,0.09,0.5,0.5
523,524,Calvin Stengs,nl NED,FW,Nice,24-152,1998,2.4,0,3,...,0.00,20.1,0.0,0,0,0.3,0.3,0.09,-0.3,-0.3
552,553,Yoann Touzghar,tn TUN,FW,Ajaccio,36-172,1986,5.0,0,3,...,NaN,11.1,0.0,0,0,0.2,0.2,0.08,-0.2,-0.2
567,568,Alan Virginius,fr FRA,FW,Lille,20-136,2003,2.9,1,12,...,0.20,14.4,0.0,0,0,3.1,3.1,0.26,-2.1,-2.1
569,570,Vitinha,pt POR,FW,Marseille,23-065,2000,4.1,2,20,...,0.29,12.1,0.0,0,0,3.5,3.5,0.18,-1.5,-1.5

In [113]:
sciezka_pliku_ligue1_shoots_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/Players_ligue1_shoots_final.xlsx'
ligue1_shoots.to_excel(sciezka_pliku_ligue1_shoots_final, index =False)

Premier League (PL)

In [114]:
sciezka_pliku_PL_shoots = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_PL_shoots.csv'
PL_shoots = pd.read_csv(sciezka_pliku_PL_shoots)

In [115]:
PL_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,-9999
0,1,Brenden Aaronson,us USA,MFFW,Leeds United,22-209,2000,25.7,1,40,...,2,0,0,3.7,3.7,0.09,-2.7,-2.7,Matches,5bc43860
1,2,Che Adams,sct SCO,FW,Southampton,26-310,1996,22.1,5,47,...,0,0,0,6.6,6.6,0.14,-1.6,-1.6,Matches,f2bf1b0f
2,3,Tyler Adams,us USA,MF,Leeds United,24-094,1999,24.0,0,4,...,0,0,0,0.1,0.1,0.03,-0.1,-0.1,Matches,2b09d998
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25-237,1997,21.2,1,13,...,1,0,0,0.6,0.6,0.05,0.4,0.4,Matches,c81d773d
4,5,Nayef Aguerd,ma MAR,DF,West Ham,27-050,1996,16.7,2,11,...,0,0,0,2.2,2.2,0.20,-0.2,-0.2,Matches,288e1e13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,555,Jordan Zemura,zw ZIM,DF,Bournemouth,23-186,1999,16.2,0,4,...,0,0,0,0.4,0.4,0.10,-0.4,-0.4,Matches,e8271ad9
555,556,Oleksandr Zinchenko,ua UKR,DF,Arsenal,26-155,1996,23.5,1,28,...,0,0,0,1.4,1.4,0.05,-0.4,-0.4,Matches,51cf8561
556,557,Hakim Ziyech,ma MAR,FWMF,Chelsea,30-061,1993,7.2,0,15,...,0,0,0,0.6,0.6,0.04,-0.6,-0.6,Matches,6622454d
557,558,Kurt Zouma,fr FRA,DF,West Ham,28-204,1994,21.6,2,19,...,0,0,0,2.2,2.2,0.12,-0.2,-0.2,Matches,ce4246f5
558,559,Martin Ødegaard,no NOR,MF,Arsenal,24-153,1998,32.9,15,91,...,8,0,0,9.9,9.9,0.11,5.1,5.1,Matches,79300479

In [116]:
del PL_shoots['Matches']
del PL_shoots['-9999']
PL_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,1,Brenden Aaronson,us USA,MFFW,Leeds United,22-209,2000,25.7,1,40,...,0.11,18.5,2,0,0,3.7,3.7,0.09,-2.7,-2.7
1,2,Che Adams,sct SCO,FW,Southampton,26-310,1996,22.1,5,47,...,0.36,13.8,0,0,0,6.6,6.6,0.14,-1.6,-1.6
2,3,Tyler Adams,us USA,MF,Leeds United,24-094,1999,24.0,0,4,...,NaN,27.5,0,0,0,0.1,0.1,0.03,-0.1,-0.1
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25-237,1997,21.2,1,13,...,0.25,21.0,1,0,0,0.6,0.6,0.05,0.4,0.4
4,5,Nayef Aguerd,ma MAR,DF,West Ham,27-050,1996,16.7,2,11,...,1.00,9.8,0,0,0,2.2,2.2,0.20,-0.2,-0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,555,Jordan Zemura,zw ZIM,DF,Bournemouth,23-186,1999,16.2,0,4,...,NaN,12.9,0,0,0,0.4,0.4,0.10,-0.4,-0.4
555,556,Oleksandr Zinchenko,ua UKR,DF,Arsenal,26-155,1996,23.5,1,28,...,0.14,22.7,0,0,0,1.4,1.4,0.05,-0.4,-0.4
556,557,Hakim Ziyech,ma MAR,FWMF,Chelsea,30-061,1993,7.2,0,15,...,0.00,22.1,0,0,0,0.6,0.6,0.04,-0.6,-0.6
557,558,Kurt Zouma,fr FRA,DF,West Ham,28-204,1994,21.6,2,19,...,0.40,10.1,0,0,0,2.2,2.2,0.12,-0.2,-0.2
558,559,Martin Ødegaard,no NOR,MF,Arsenal,24-153,1998,32.9,15,91,...,0.48,19.0,8,0,0,9.9,9.9,0.11,5.1,5.1

In [117]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AM,FW'
pos_4 = 'FW,AM'
PL_shoots = PL_shoots[(PL_shoots['Pos'] == pos_1) | (PL_shoots['Pos'] == pos_2) | (PL_shoots['Pos'] == pos_3) | (PL_shoots['Pos'] == pos_4)]
PL_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
1,2,Che Adams,sct SCO,FW,Southampton,26-310,1996,22.1,5,47,...,0.36,13.8,0,0,0,6.6,6.6,0.14,-1.6,-1.6
16,17,Miguel Almirón,py PAR,FW,Newcastle Utd,29-098,1994,25.7,11,60,...,0.61,16.3,0,0,0,6.9,6.9,0.12,4.1,4.1
22,23,Michail Antonio,jm JAM,FW,West Ham,33-052,1990,19.6,5,37,...,0.42,11.2,0,0,0,6.4,6.4,0.18,-1.4,-1.4
23,24,Antony,br BRA,FW,Manchester Utd,23-084,2000,18.8,4,68,...,0.17,19.6,0,0,0,6.4,6.4,0.09,-2.4,-2.4
30,31,Pierre-Emerick Aubameyang,ga GAB,FW,Chelsea,33-335,1989,6.2,1,16,...,0.14,13.7,0,0,0,1.5,1.5,0.09,-0.5,-0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,542,Callum Wilson,eng ENG,FW,Newcastle Utd,31-081,1992,19.9,18,66,...,0.48,12.8,0,3,3,16.9,14.6,0.22,1.1,0.4
542,543,Harry Wilson,wls WAL,FW,Fulham,26-058,1997,10.6,2,16,...,0.50,16.1,0,0,0,1.8,1.8,0.11,0.2,0.2
543,544,Yoane Wissa,cd COD,FW,Brentford,26-258,1996,15.9,6,30,...,0.43,14.1,0,0,0,4.9,4.9,0.16,1.1,1.1
545,546,Chris Wood,nz NZL,FW,Newcastle Utd,31-163,1991,5.0,2,8,...,0.33,14.7,0,1,1,1.8,1.0,0.13,0.2,0.0
546,547,Chris Wood,nz NZL,FW,Nott'ham Forest,31-163,1991,4.1,1,3,...,1.00,8.2,0,0,0,1.0,1.0,0.32,0.0,0.0

In [118]:
sciezka_pliku_PL_shoots_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/Players_PL_shoots_final.xlsx'
PL_shoots.to_excel(sciezka_pliku_PL_shoots_final, index =False)

Serie A

In [119]:
sciezka_pliku_SerieA_shoots = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/Players_Serie A_shoots.csv'
SerieA_shoots = pd.read_csv(sciezka_pliku_SerieA_shoots)
SerieA_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches,-9999
0,1,James Abankwah,ie IRL,DF,Udinese,19-123,2004,0.1,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,4b7a9fcc
1,2,Oliver Abildgaard,dk DEN,MF,Hellas Verona,26-343,1996,6.2,0,3,...,0.0,0,0,0.1,0.1,0.05,-0.1,-0.1,Matches,8f5cdf66
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,8,61,...,0.0,0,0,10.8,10.8,0.18,-2.8,-2.8,Matches,f586779e
3,4,Christian Acella,it ITA,MF,Cremonese,20-316,2002,0.2,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,771a2cfe
4,5,Francesco Acerbi,it ITA,DF,Inter,35-098,1988,25.3,0,16,...,0.0,0,0,0.8,0.8,0.05,-0.8,-0.8,Matches,b96b595c
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Petar Zovko,ba BIH,GK,Spezia,21-055,2002,0.8,0,0,...,0.0,0,0,0.0,0.0,NaN,0.0,0.0,Matches,54f6afe3
581,582,Szymon Żurkowski,pl POL,MF,Fiorentina,25-236,1997,0.4,0,2,...,0.0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches,4e1d5e59
582,583,Szymon Żurkowski,pl POL,MF,Spezia,25-236,1997,3.0,0,3,...,0.0,0,0,0.1,0.1,0.04,-0.1,-0.1,Matches,4e1d5e59
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,1,15,...,0.0,0,0,1.4,1.4,0.09,-0.4,-0.4,Matches,405f6586
584,585,Filip Đuričić,rs SRB,MFFW,Sampdoria,31-109,1992,23.2,3,25,...,1.0,0,0,2.6,2.6,0.10,0.4,0.4,Matches,eccbe56a

In [120]:
del SerieA_shoots['Matches']
del SerieA_shoots['-9999']
SerieA_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,1,James Abankwah,ie IRL,DF,Udinese,19-123,2004,0.1,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
1,2,Oliver Abildgaard,dk DEN,MF,Hellas Verona,26-343,1996,6.2,0,3,...,0.00,14.0,0.0,0,0,0.1,0.1,0.05,-0.1,-0.1
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,8,61,...,0.30,12.0,0.0,0,0,10.8,10.8,0.18,-2.8,-2.8
3,4,Christian Acella,it ITA,MF,Cremonese,20-316,2002,0.2,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
4,5,Francesco Acerbi,it ITA,DF,Inter,35-098,1988,25.3,0,16,...,0.00,15.7,0.0,0,0,0.8,0.8,0.05,-0.8,-0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,581,Petar Zovko,ba BIH,GK,Spezia,21-055,2002,0.8,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
581,582,Szymon Żurkowski,pl POL,MF,Fiorentina,25-236,1997,0.4,0,2,...,0.00,15.2,0.0,0,0,0.1,0.1,0.06,-0.1,-0.1
582,583,Szymon Żurkowski,pl POL,MF,Spezia,25-236,1997,3.0,0,3,...,0.00,22.3,0.0,0,0,0.1,0.1,0.04,-0.1,-0.1
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,1,15,...,0.20,10.9,0.0,0,0,1.4,1.4,0.09,-0.4,-0.4
584,585,Filip Đuričić,rs SRB,MFFW,Sampdoria,31-109,1992,23.2,3,25,...,0.27,18.6,1.0,0,0,2.6,2.6,0.10,0.4,0.4

In [121]:
pos_1 = 'AM'
pos_2 = 'FW'
pos_3 = 'AM,FW'
pos_4 = 'FW,AM'
SerieA_shoots = SerieA_shoots[(SerieA_shoots['Pos'] == pos_1) | (SerieA_shoots['Pos'] == pos_2) | (SerieA_shoots['Pos'] == pos_3) | (SerieA_shoots['Pos'] == pos_4)]
SerieA_shoots

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
2,3,Tammy Abraham,eng ENG,FW,Roma,25-229,1997,23.7,8,61,...,0.30,12.0,0.0,0,0,10.8,10.8,0.18,-2.8,-2.8
19,20,Felipe Anderson,br BRA,FW,Lazio,30-034,1993,31.0,9,39,...,0.41,14.5,0.0,0,0,6.0,6.0,0.15,3.0,3.0
20,21,Janis Antiste,fr FRA,FW,Sassuolo,20-274,2002,0.6,1,1,...,1.00,17.3,0.0,0,0,0.2,0.2,0.18,0.8,0.8
23,24,Marko Arnautović,at AUT,FW,Bologna,34-030,1989,14.7,8,22,...,0.45,16.1,0.0,3,3,5.7,3.4,0.15,2.3,1.6
25,26,Arthur,br BRA,FW,Fiorentina,25-024,1998,14.9,7,48,...,0.29,12.6,0.0,2,2,7.2,5.7,0.12,-0.2,-0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,560,Mattia Zaccagni,it ITA,FW,Lazio,27-337,1995,28.5,10,51,...,0.41,16.9,1.0,1,1,6.3,5.5,0.11,3.7,3.5
568,569,Duván Zapata,co COL,FW,Atalanta,32-048,1991,15.5,2,41,...,0.25,15.6,0.0,0,0,3.9,3.9,0.10,-1.9,-1.9
573,574,Alessio Zerbin,it ITA,FW,Napoli,24-077,1999,1.3,0,3,...,0.00,18.5,0.0,0,0,0.1,0.1,0.04,-0.1,-0.1
576,577,Joshua Zirkzee,nl NED,FW,Bologna,21-362,2001,8.6,1,27,...,0.14,16.2,0.0,0,0,3.0,3.0,0.11,-2.0,-2.0
583,584,Milan Đurić,ba BIH,FW,Hellas Verona,32-362,1990,12.8,1,15,...,0.20,10.9,0.0,0,0,1.4,1.4,0.09,-0.4,-0.4

In [122]:
sciezka_pliku_SerieA_shoots_final = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/Players_SerieA_shoots_final.xlsx'
SerieA_shoots.to_excel(sciezka_pliku_SerieA_shoots_final, index =False)

scalanie plików

In [123]:
import glob
folder_path = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/'
files_xlsx = glob.glob(folder_path + '*.xlsx')
df_list =[]
for file in files_xlsx:
    df = pd.read_excel(file)
    df_list.append(df)
df_combined = pd.concat(df_list)
path_output_file = 'C:/Users/Daniel/Documents/STUDIA PODYPLOMOWE/Seminarium-projekt końcowy/po_filtr_strz/All_players_shoots.xlsx'
df_combined.to_excel(path_output_file, index=False)